/*
 * This file is part of FNFT.
 *
 * FNFT is free software; you can redistribute it and/or
 * modify it under the terms of the version 2 of the GNU General
 * Public License as published by the Free Software Foundation.
 *
 * FNFT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * Contributors:
 * Igor Chekhovskoy (NSU, FRC ICT) 2026.
 * Irina Vaseva (FRC ICT, NSU) 2026.
 */
#define FNFT_ENABLE_SHORT_NAMES

#include "fnft__nse_scatter.h"
#include "fnft__nse_discretization.h"
#include "fnft__misc.h"
#include "fnft__errwarn.h"

#include <float.h>
#include <stdlib.h>

/* Values generated by the independent NFT_ES8 implementation in integrate.h,
 * which is a direct transcription of Eqs. 51--60 of arXiv:2608.11892v1. */
static INT test_paper_coefficients(void)
{
    const COMPLEX q[7] = {0.13 + 0.02 * I,    -0.07 + 0.03 * I,   0.011 - 0.04 * I,
                          0.021 + 0.013 * I,  -0.008 + 0.006 * I, 0.003 - 0.002 * I,
                          -0.001 + 0.0004 * I};
    const COMPLEX r[7] = {-0.09 + 0.04 * I,   0.05 + 0.01 * I,   -0.014 - 0.009 * I,
                          0.006 - 0.003 * I,  0.002 + 0.004 * I, -0.001 - 0.0007 * I,
                          0.0003 + 0.0002 * I};
    const COMPLEX expected[24] = {-0.00010639014375158731 - 0.00064626268636944456 * I,
                                  0.13045199977447222 + 0.01833438298798809 * I,
                                  -0.090581002308626979 + 0.039624854004361117 * I,
                                  0.00010639014375158731 + 0.00064626268636944456 * I,
                                  6.6029439153439124e-6 - 0.99993973629338628 * I,
                                  -0.0050608385946560846 - 0.011587297410899472 * I,
                                  0.0016534792394444454 - 0.0083654412335978836 * I,
                                  -6.6029439153439124e-6 + 0.99993973629338628 * I,
                                  -7.1421507936507912e-6 - 4.4202031746031749e-5 * I,
                                  -6.0792142857142867e-5 + 0.00022172208994708997 * I,
                                  7.7978121693121703e-5 + 4.9306851851851839e-5 * I,
                                  7.1421507936507912e-6 + 4.4202031746031749e-5 * I,
                                  1.0079365079365077e-6 + 7.7698412698412717e-6 * I,
                                  -0.00033721005291005281 - 0.00077524708994708999 * I,
                                  0.00011042063492063491 - 0.00055814074074074071 * I,
                                  -1.0079365079365077e-6 - 7.7698412698412717e-6 * I,
                                  -6.3492063492063518e-7 - 4.1269841269841268e-6 * I,
                                  -5.8201058201058197e-6 + 2.1164021164021168e-5 * I,
                                  7.4074074074074083e-6 + 4.7619047619047624e-6 * I,
                                  6.3492063492063518e-7 + 4.1269841269841268e-6 * I,
                                  0.0,
                                  -3.1746031746031745e-5 - 7.4074074074074087e-5 * I,
                                  1.0582010582010584e-5 - 5.2910052910052919e-5 * I,
                                  0.0};
    const COMPLEX lambda = 0.31 + 0.17 * I;
    const COMPLEX expected_U[4] = {1.0151223081156064 - 0.039982507188694998 * I,
                                   0.13020129924855509 + 0.017752739161081763 * I,
                                   -0.090134938490682354 + 0.039208908505235708 * I,
                                   0.97121375302911384 + 0.041705781954501898 * I};
    COMPLEX coeff[24], U[4];
    fnft__akns_es8_z_coefficients(q, r, coeff);
    if (misc_rel_err(24, coeff, expected) > 10 * EPSILON)
        return E_TEST_FAILED;
    if (nse_scatter_matrix(7, q, r, 0.13, +1, 1, &lambda, U, NULL, nse_discretization_ES8, 0) !=
        SUCCESS)
        return E_TEST_FAILED;
    return misc_rel_err(4, U, expected_U) <= 20 * EPSILON ? SUCCESS : E_TEST_FAILED;
}

static INT test_es_family_traceless_coefficients(void)
{
    const COMPLEX q[7] = {
        0.13+0.02*(COMPLEX)I, -0.07+0.03*(COMPLEX)I,
        0.011-0.04*(COMPLEX)I, 0.021+0.013*(COMPLEX)I,
        -0.008+0.006*(COMPLEX)I, 0.003-0.002*(COMPLEX)I,
        -0.001+0.0004*(COMPLEX)I
    };
    const COMPLEX r[7] = {
        -0.09+0.04*(COMPLEX)I, 0.05+0.01*(COMPLEX)I,
        -0.014-0.009*(COMPLEX)I, 0.006-0.003*(COMPLEX)I,
        0.002+0.004*(COMPLEX)I, -0.001-0.0007*(COMPLEX)I,
        0.0003+0.0002*(COMPLEX)I
    };
    const COMPLEX z_values[4] = {
        0.0, 1e-100*(1.0+(COMPLEX)I), 0.27+0.31*(COMPLEX)I,
        1e4-2e4*(COMPLEX)I
    };
    const UINT orders[3] = {4,6,8};

    for (UINT method=0; method<3; method++) {
        const UINT degree = orders[method]-3;
        COMPLEX coeff[24] = {0};

        fnft__akns_es_z_coefficients(orders[method],q,r,coeff);
        for (UINT k=0; k<=degree; k++) {
            if (!isfinite(CREAL(coeff[4*k]))
                    || !isfinite(CIMAG(coeff[4*k]))
                    || coeff[4*k+3] != -coeff[4*k])
                return E_TEST_FAILED;
        }
        for (UINT point=0; point<4; point++) {
            COMPLEX Z0 = coeff[4*degree], Z3 = coeff[4*degree+3];
            COMPLEX Zd0 = degree*coeff[4*degree];
            COMPLEX Zd3 = degree*coeff[4*degree+3];

            for (UINT k=degree; k-->0; ) {
                Z0 = Z0*z_values[point]+coeff[4*k];
                Z3 = Z3*z_values[point]+coeff[4*k+3];
            }
            for (UINT k=degree; k-->1; ) {
                Zd0 = Zd0*z_values[point]+k*coeff[4*k];
                Zd3 = Zd3*z_values[point]+k*coeff[4*k+3];
            }
            {
                const REAL value_error = CABS(Z3+Z0);
                const REAL derivative_error = CABS(Zd3+Zd0);
                const REAL value_tolerance = 50*EPSILON
                        *(1+CABS(Z0)+CABS(Z3));
                const REAL derivative_tolerance = 50*EPSILON
                        *(1+CABS(Zd0)+CABS(Zd3));

                if (!isfinite(CREAL(Z0)) || !isfinite(CIMAG(Z0))
                        || !isfinite(CREAL(Z3)) || !isfinite(CIMAG(Z3))
                        || !isfinite(CREAL(Zd0)) || !isfinite(CIMAG(Zd0))
                        || !isfinite(CREAL(Zd3)) || !isfinite(CIMAG(Zd3))
                        || !isfinite(value_error)
                        || !isfinite(derivative_error)
                        || !isfinite(value_tolerance)
                        || !isfinite(derivative_tolerance)
                        || !(value_error <= value_tolerance)
                        || !(derivative_error <= derivative_tolerance))
                    return E_TEST_FAILED;
            }
        }
    }
    return SUCCESS;
}

static void reference_exact_scalar_pair(COMPLEX const delta,
        COMPLEX * const f, COMPLEX * const g,
        COMPLEX * const f_delta)
{
    if (CABS(delta) < 1e-8) {
        const COMPLEX delta2 = delta*delta;
        const COMPLEX delta3 = delta2*delta;
        const COMPLEX delta4 = delta3*delta;

        *f = 1.0+delta/2.0+delta2/24.0+delta3/720.0
                +delta4/40320.0;
        *g = 1.0+delta/6.0+delta2/120.0+delta3/5040.0
                +delta4/362880.0;
        *f_delta = 1.0/6.0+delta/60.0+delta2/1680.0
                +delta3/90720.0;
    } else {
        const COMPLEX root = CSQRT(delta);

        *f = CCOSH(root);
        *g = misc_CSINC((COMPLEX)I*root);
        *f_delta = (*f-*g)/(2.0*delta);
    }
}

static INT check_exact_scalar_value(COMPLEX const actual,
                                    COMPLEX const expected,
                                    UINT const signed_zero_flag)
{
    const REAL actual_parts[2] = {CREAL(actual),CIMAG(actual)};
    const REAL expected_parts[2] = {CREAL(expected),CIMAG(expected)};

    for (UINT part=0; part<2; part++) {
        if (isnan(expected_parts[part])) {
            if (!isnan(actual_parts[part]))
                return E_TEST_FAILED;
        } else if (isinf(expected_parts[part])) {
            if (!isinf(actual_parts[part])
                    || signbit(actual_parts[part])
                        != signbit(expected_parts[part]))
                return E_TEST_FAILED;
        } else {
            if (!isfinite(actual_parts[part]))
                return E_TEST_FAILED;
            if (signed_zero_flag && expected_parts[part] == 0.0
                    && actual_parts[part] == 0.0
                    && signbit(actual_parts[part])
                        != signbit(expected_parts[part]))
                return E_TEST_FAILED;
        }
    }
    if (isfinite(expected_parts[0]) && isfinite(expected_parts[1])) {
        const REAL error = CABS(actual-expected);
        const REAL scale = fmax(1.0,fmax(FABS(expected_parts[0]),
                FABS(expected_parts[1])));
        const REAL tolerance = 256*EPSILON*scale;

        if (!isfinite(error) || !isfinite(tolerance)
                || !(error <= tolerance))
            return E_TEST_FAILED;
    }
    return SUCCESS;
}

static COMPLEX reference_complex_multiply(COMPLEX const a,
                                          COMPLEX const b)
{
    return a*b;
}

static COMPLEX reference_complex_multiply_add(COMPLEX const a,
        COMPLEX const b, COMPLEX const c)
{
    return a+b*c;
}

static COMPLEX complex_from_parts(REAL const real, REAL const imag)
{
    const REAL parts[2] = {real,imag};
    COMPLEX value;

    memcpy(&value,parts,sizeof(value));
    return value;
}

static INT test_exact_scalar_pair_shared_hyperbolics(void)
{
    const REAL re[] = {-700.0,-100.0,-20.0,-1.0,-0.1,-1e-12,-1e-300,
            -0.0,0.0,1e-300,1e-12,0.1,1.0,20.0,100.0,700.0};
    const REAL im[] = {-1e6,-3.0,-0.1,-1e-12,-0.0,0.0,1e-12,0.1,3.0,1e6};

    for (UINT i=0; i<sizeof(re)/sizeof(re[0]); i++) {
        for (UINT j=0; j<sizeof(im)/sizeof(im[0]); j++) {
            const COMPLEX root = complex_from_parts(re[i],im[j]);
            const COMPLEX reference[2] = {CCOSH(root),misc_CSINC((COMPLEX)I*root)};
            COMPLEX actual[2];

            fnft__akns_scatter_exact_scalar_pair(root,&actual[0],&actual[1]);
            for (UINT k=0; k<2; k++) {
                const REAL scale = fmax(1.0,fmax(FABS(CREAL(reference[k])),
                        FABS(CIMAG(reference[k]))));
                if (!isfinite(CREAL(actual[k])) || !isfinite(CIMAG(actual[k]))
                        || !(CABS(actual[k]-reference[k]) <= 16*EPSILON*scale))
                    return E_TEST_FAILED;
            }
        }
    }
    return SUCCESS;
}

static INT test_exact_scalar_pair_signed_zeros(void)
{
    const COMPLEX roots[] = {
        complex_from_parts(0.0,0.0),
        complex_from_parts(-0.0,0.0),
        complex_from_parts(0.0,-0.0),
        complex_from_parts(-0.0,-0.0),
        complex_from_parts(1.0,0.0),
        complex_from_parts(1.0,-0.0),
        complex_from_parts(0.0,1.0),
        complex_from_parts(-0.0,1.0),
        complex_from_parts(0.0,-1.0),
        complex_from_parts(-0.0,-1.0),
        complex_from_parts(1.0,1.0),
        complex_from_parts(1.0,-1.0),
        CSQRT(1e300), CSQRT(-1e300),
        complex_from_parts(-0.0,1e150),
        complex_from_parts(0.0,-1e150),
        complex_from_parts(-0.0,-1e150),
        CSQRT(1e300+(COMPLEX)I*1e300),
        complex_from_parts(INFINITY,0.0),
        complex_from_parts(NAN,1.0)
    };
    UINT signbit_checks = 0;

    for (UINT point=0; point<sizeof(roots)/sizeof(roots[0]); point++) {
        COMPLEX actual_f, actual_g;
        const COMPLEX expected_f = CCOSH(roots[point]);
        const COMPLEX expected_g = misc_CSINC((COMPLEX)I*roots[point]);
        const REAL expected_parts[4] = {
            CREAL(expected_f),CIMAG(expected_f),
            CREAL(expected_g),CIMAG(expected_g)
        };
        REAL actual_parts[4];
        INT ret_code;

        fnft__akns_scatter_exact_scalar_pair(roots[point],
                &actual_f,&actual_g);
        actual_parts[0] = CREAL(actual_f);
        actual_parts[1] = CIMAG(actual_f);
        actual_parts[2] = CREAL(actual_g);
        actual_parts[3] = CIMAG(actual_g);
        ret_code = check_exact_scalar_value(actual_f,expected_f,1);
        if (ret_code == SUCCESS)
            ret_code = check_exact_scalar_value(actual_g,expected_g,1);
        if (ret_code != SUCCESS)
            return ret_code;
        for (UINT part=0; part<4; part++) {
            if (expected_parts[part] == 0.0) {
                signbit_checks++;
                if (actual_parts[part] != 0.0
                        || signbit(actual_parts[part])
                            != signbit(expected_parts[part]))
                    return E_TEST_FAILED;
            }
        }
    }
    return signbit_checks >= 20 ? SUCCESS : E_TEST_FAILED;
}

static INT test_exact_scalar_pair_derivative_grid(void)
{
    const COMPLEX targets[] = {
        0.5e-8, 2.0e-8, 1.0+0.3*(COMPLEX)I,
        490000.0+1e-6*(COMPLEX)I,
        500000.0+1e-6*(COMPLEX)I
    };
    const COMPLEX lambda = 1.0/1024.0;

    for (UINT point=0; point<sizeof(targets)/sizeof(targets[0]); point++) {
        const COMPLEX potential = CSQRT(targets[point]+lambda*lambda);
        COMPLEX q[3] = {potential,0.0,0.0};
        COMPLEX r[3] = {potential,0.0,0.0};
        COMPLEX coeff[8], Z[4], Zd[4], actual[8], expected[8];
        COMPLEX f, g, signed_g, f_delta, f_d, g_d, delta, delta_d;
        COMPLEX (* volatile multiply)(COMPLEX,COMPLEX) =
                reference_complex_multiply;
        COMPLEX (* volatile multiply_add)(COMPLEX,COMPLEX,COMPLEX) =
                reference_complex_multiply_add;
        INT ret_code;

        fnft__akns_es_z_coefficients(4,q,r,coeff);
        for (UINT j=0; j<4; j++) {
            Z[j] = multiply_add(coeff[j],coeff[4+j],lambda);
            Zd[j] = coeff[4+j];
        }
        delta = multiply(Z[0],Z[0])+multiply(Z[1],Z[2]);
        delta_d = multiply(2.0*multiply(Z[0],Zd[0]),1.0)
                +multiply(Zd[1],Z[2])+multiply(Z[1],Zd[2]);
        if (!isfinite(CREAL(delta_d)) || !isfinite(CIMAG(delta_d))
                || CABS(delta_d) == 0.0)
            return E_TEST_FAILED;
        reference_exact_scalar_pair(delta,&f,&g,&f_delta);
        signed_g = multiply((COMPLEX)1.0,g);
        f_d = multiply(0.5*g,delta_d);
        g_d = multiply(f_delta,delta_d);
        expected[0] = multiply_add(f,signed_g,Z[0]);
        expected[1] = multiply(signed_g,Z[1]);
        expected[2] = multiply(signed_g,Z[2]);
        expected[3] = multiply_add(f,signed_g,Z[3]);
        expected[4] = multiply_add(f_d,(COMPLEX)1.0,
                multiply(g_d,Z[0])+multiply(g,Zd[0]));
        expected[5] = multiply((COMPLEX)1.0,
                multiply(g_d,Z[1])+multiply(g,Zd[1]));
        expected[6] = multiply((COMPLEX)1.0,
                multiply(g_d,Z[2])+multiply(g,Zd[2]));
        expected[7] = multiply_add(f_d,(COMPLEX)1.0,
                multiply(g_d,Z[3])+multiply(g,Zd[3]));
        ret_code = nse_scatter_matrix(3,q,r,1.0,+1,1,&lambda,actual,NULL,
                nse_discretization_ES4,1);
        CHECK_RETCODE(ret_code, leave_fun);
        for (UINT j=0; j<8; j++) {
            ret_code = check_exact_scalar_value(actual[j],expected[j],0);
            if (ret_code != SUCCESS) {
                fprintf(stderr,"scalar derivative grid point=%lu "
                        "component=%lu delta=(%.17g,%.17g) "
                        "delta_d=(%.17g,%.17g) actual=(%.17g,%.17g) "
                        "expected=(%.17g,%.17g)\n",
                        (unsigned long)point,(unsigned long)j,
                        CREAL(delta),CIMAG(delta),CREAL(delta_d),
                        CIMAG(delta_d),CREAL(actual[j]),CIMAG(actual[j]),
                        CREAL(expected[j]),CIMAG(expected[j]));
                goto leave_fun;
            }
        }
    }
    return SUCCESS;

leave_fun:
    return E_TEST_FAILED;
}

/* A one-node ES4 step with lambda=0 and Z=[0,1;delta,0] exposes the
 * scalar pair through U00=f and U01=g. This retains the previous complex
 * library calls as an independent reference and also checks propagated U'. */
static INT test_exact_scalar_pair_grid(void)
{
    const REAL pi = acos(-1.0);
    const COMPLEX deltas[] = {
        0.0, -0.0, 0.0-(COMPLEX)I*0.0, -0.0-(COMPLEX)I*0.0,
        DBL_MIN/2.0, 0.5e-8, nextafter(1e-8,0.0), 1e-8,
        nextafter(1e-8,INFINITY), 1.0, -1.0,
        (COMPLEX)I, -(COMPLEX)I, 1.0+(COMPLEX)I,
        1.0-(COMPLEX)I, -1.0+(COMPLEX)I, -1.0-(COMPLEX)I,
        -pi*pi, -(pi-1e-8)*(pi-1e-8),
        -(pi+1e-8)*(pi+1e-8), 1e4, -1e4,
        1e4+1e4*(COMPLEX)I,
        NAN, INFINITY, -INFINITY, NAN+(COMPLEX)I,
        1.0+(COMPLEX)I*INFINITY
    };
    const COMPLEX lambda = 0.0;

    for (UINT point=0; point<sizeof(deltas)/sizeof(deltas[0]); point++) {
        COMPLEX q[3] = {1.0,0.0,0.0};
        COMPLEX r[3] = {deltas[point],0.0,0.0};
        COMPLEX actual[8], f, g, f_delta, expected[8];
        volatile COMPLEX Z_reference[4] = {
            0.0,1.0,deltas[point],-0.0
        };
        volatile COMPLEX Zd_reference[4] = {
            -(COMPLEX)I,0.0,0.0,(COMPLEX)I
        };
        const COMPLEX z0 = Z_reference[0], z1 = Z_reference[1];
        const COMPLEX z2 = Z_reference[2], z3 = Z_reference[3];
        const COMPLEX zd0 = Zd_reference[0], zd1 = Zd_reference[1];
        const COMPLEX zd2 = Zd_reference[2], zd3 = Zd_reference[3];
        COMPLEX (* volatile multiply)(COMPLEX,COMPLEX) =
                reference_complex_multiply;
        COMPLEX (* volatile multiply_add)(COMPLEX,COMPLEX,COMPLEX) =
                reference_complex_multiply_add;
        const COMPLEX delta_reference = multiply(z0,z0)+multiply(z1,z2);
        const COMPLEX delta_d = multiply(2.0*multiply(z0,zd0),1.0)
                +multiply(zd1,z2)+multiply(z1,zd2);
        COMPLEX f_d, g_d;
        INT ret_code;

        reference_exact_scalar_pair(delta_reference,&f,&g,&f_delta);
        f_d = multiply(0.5*g,delta_d);
        g_d = multiply(f_delta,delta_d);
        expected[0] = multiply_add(f,g,z0);
        expected[1] = multiply(g,z1);
        expected[2] = multiply(g,z2);
        expected[3] = multiply_add(f,g,z3);
        expected[4] = multiply_add(multiply_add(f_d,g_d,z0),g,zd0);
        expected[5] = multiply(g_d,z1);
        expected[6] = multiply(g_d,z2);
        expected[7] = multiply_add(multiply_add(f_d,g_d,z3),g,zd3);
        ret_code = nse_scatter_matrix(3,q,r,1.0,+1,1,&lambda,actual,NULL,
                nse_discretization_ES4,1);
        CHECK_RETCODE(ret_code, leave_fun);
        for (UINT j=0; j<8; j++) {
            /* Matrix materialization/multiplication may canonicalize signed
             * zeros even when the scalar pair retains them. */
            ret_code = check_exact_scalar_value(actual[j],expected[j],0);
            if (ret_code != SUCCESS) {
                fprintf(stderr,"scalar pair grid point=%lu component=%lu "
                        "delta=(%.17g,%.17g) actual=(%.17g,%.17g) "
                        "expected=(%.17g,%.17g)\n",
                        (unsigned long)point,(unsigned long)j,
                        CREAL(deltas[point]),CIMAG(deltas[point]),
                        CREAL(actual[j]),CIMAG(actual[j]),
                        CREAL(expected[j]),CIMAG(expected[j]));
                goto leave_fun;
            }
        }
    }
    return SUCCESS;

leave_fun:
    return E_TEST_FAILED;
}

/* The full scattering-matrix path applies a change of basis after U. Near
 * overflow that later algebra can introduce Inf-Inf independently of the
 * scalar pair. The ES first-column path has no such change of basis. A
 * balanced Z01=Z10=sqrt(delta) keeps both off-diagonal entries finite up to
 * the fallback boundary. For nonfinite inputs, form the reference with the
 * same matrix-vector algebra and compare its classification fail-closed. */
static INT test_exact_scalar_pair_extremes(void)
{
    const REAL safe_root = log(DBL_MAX)-8.0;
    const COMPLEX deltas[] = {
        safe_root*safe_root,
        (safe_root+1.0)*(safe_root+1.0),
        490000.0+(COMPLEX)I*1e-6,
        500000.0+(COMPLEX)I*1e-6,
        1e300, -1e300, 1e300+(COMPLEX)I*1e300,
        INFINITY, NAN+(COMPLEX)I
    };
    const COMPLEX lambda = 0.0;

    for (UINT point=0; point<sizeof(deltas)/sizeof(deltas[0]); point++) {
        const COMPLEX root = CSQRT(deltas[point]);
        COMPLEX q[3] = {root,0.0,0.0};
        COMPLEX r[3] = {root,0.0,0.0};
        COMPLEX coeff[8], actual_f, actual_g, expected_f, expected_g;
        COMPLEX f, g, f_delta, expected_materialized_f;
        COMPLEX expected_materialized_g, recovered_g;
        COMPLEX (* volatile multiply)(COMPLEX,COMPLEX) =
                reference_complex_multiply;
        COMPLEX (* volatile multiply_add)(COMPLEX,COMPLEX,COMPLEX) =
                reference_complex_multiply_add;
        COMPLEX delta_reference;
        INT ret_code;

        fnft__akns_es_z_coefficients(4,q,r,coeff);
        delta_reference = multiply(coeff[0],coeff[0])
                +multiply(coeff[1],coeff[2]);
        reference_exact_scalar_pair(delta_reference,&f,&g,&f_delta);
        expected_f = multiply_add(f,g,coeff[0]);
        expected_g = multiply(g,coeff[2]);
        expected_materialized_f = multiply_add(expected_f,
                multiply(g,coeff[1]),0.0);
        expected_materialized_g = multiply_add(expected_g,
                multiply_add(f,g,coeff[3]),0.0);
        ret_code = akns_scatter_matrix_first_column(3,q,r,1.0,1,&lambda,
                &actual_f,&actual_g,NULL,akns_discretization_ES4,0);
        CHECK_RETCODE(ret_code, leave_fun);
        ret_code = check_exact_scalar_value(actual_f,
                expected_materialized_f,0);
        if (ret_code == SUCCESS)
            ret_code = check_exact_scalar_value(actual_g,
                    expected_materialized_g,0);
        if (ret_code == SUCCESS && isfinite(CREAL(root))
                && isfinite(CIMAG(root)) && CABS(root) != 0.0
                && isfinite(CREAL(actual_g))
                && isfinite(CIMAG(actual_g))) {
            recovered_g = actual_g/root;
            ret_code = check_exact_scalar_value(recovered_g,g,0);
        }
        if (ret_code != SUCCESS) {
            fprintf(stderr,"scalar pair extreme point=%lu "
                    "delta=(%.17g,%.17g) f=(%.17g,%.17g) "
                    "f_ref=(%.17g,%.17g) g=(%.17g,%.17g) "
                    "g_ref=(%.17g,%.17g)\n",
                    (unsigned long)point,CREAL(deltas[point]),
                    CIMAG(deltas[point]),CREAL(actual_f),CIMAG(actual_f),
                    CREAL(expected_materialized_f),
                    CIMAG(expected_materialized_f),CREAL(actual_g),
                    CIMAG(actual_g),CREAL(expected_materialized_g),
                    CIMAG(expected_materialized_g));
            goto leave_fun;
        }
    }
    return SUCCESS;

leave_fun:
    return E_TEST_FAILED;
}

static void es8_pack(COMPLEX const f[7], REAL const h, COMPLEX out[7])
{
    out[0] = h * f[3];
    out[1] = h * (-f[0] / 60.0 + 3.0 * f[1] / 20.0 - 3.0 * f[2] / 4.0 + 3.0 * f[4] / 4.0 -
                  3.0 * f[5] / 20.0 + f[6] / 60.0);
    out[2] = h * (f[0] / 90.0 - 3.0 * f[1] / 20.0 + 3.0 * f[2] / 2.0 - 49.0 * f[3] / 18.0 +
                  3.0 * f[4] / 2.0 - 3.0 * f[5] / 20.0 + f[6] / 90.0);
    out[3] = h * (f[0] / 8.0 - f[1] + 13.0 * f[2] / 8.0 - 13.0 * f[4] / 8.0 + f[5] - f[6] / 8.0);
    out[4] = h * (-f[0] / 6.0 + 2.0 * f[1] - 13.0 * f[2] / 2.0 + 28.0 * f[3] / 3.0 -
                  13.0 * f[4] / 2.0 + 2.0 * f[5] - f[6] / 6.0);
    out[5] = h * (-f[0] / 2.0 + 2.0 * f[1] - 5.0 * f[2] / 2.0 + 5.0 * f[4] / 2.0 - 2.0 * f[5] +
                  f[6] / 2.0);
    out[6] = h * (f[0] - 6.0 * f[1] + 15.0 * f[2] - 20.0 * f[3] + 15.0 * f[4] - 6.0 * f[5] + f[6]);
}

static INT test_scatter_matrix(const UINT D,
        COMPLEX const * const q, COMPLEX const * const r,
        const REAL eps_t, const INT kappa, const UINT K,
        COMPLEX const * const lambda, COMPLEX * const result,
        INT * const W, const nse_discretization_t discretization,
        const UINT pade_degree, const UINT derivative_flag)
{
    if (pade_degree > 0)
        return nse_scatter_matrix_pade(D,q,r,eps_t,kappa,K,lambda,result,W,
                discretization,pade_degree,derivative_flag);
    return nse_scatter_matrix(D,q,r,eps_t,kappa,K,lambda,result,W,
            discretization,derivative_flag);
}

static INT test_scatter_bound_states(const UINT D,
        COMPLEX const * const q, COMPLEX const * const r,
        REAL const T[2], const COMPLEX bound_state,
        COMPLEX * const a, COMPLEX * const aprime, COMPLEX * const b,
        INT * const W, const nse_discretization_t discretization,
        const UINT pade_degree)
{
    COMPLEX state = bound_state;

    if (pade_degree > 0)
        return nse_scatter_bound_states_pade(D,q,r,T,1,&state,a,aprime,b,
                W,discretization,pade_degree,0);
    return nse_scatter_bound_states(D,q,r,T,1,&state,a,aprime,b,W,
            discretization,0);
}

static INT test_stencil_and_boundaries(void)
{
    const REAL h = 0.07;
    const COMPLEX samples[7] = {0.17 - 0.03 * I, 0.25 + 0.07 * I, 0.38 - 0.11 * I, 0.51 + 0.09 * I,
                                0.47 - 0.05 * I, 0.34 + 0.02 * I, 0.21 - 0.08 * I};
    const COMPLEX left_samples[7] = {0.0, 0.0, 0.0, samples[0], samples[1], samples[2], samples[3]};
    COMPLEX expected[7], *q_preprocessed = NULL, *r_preprocessed = NULL;
    UINT Dsub = 7, first_last_index[2];
    INT ret_code;

    ret_code = nse_discretization_preprocess_signal(7, samples, h, +1, &Dsub, &q_preprocessed,
                                                    &r_preprocessed, first_last_index,
                                                    nse_discretization_ES8);
    CHECK_RETCODE(ret_code, leave_fun);
    if (Dsub != 7 || first_last_index[0] != 0 || first_last_index[1] != 6) {
        ret_code = E_TEST_FAILED;
        goto leave_fun;
    }
    es8_pack(samples, h, expected);
    if (misc_rel_err(7, &q_preprocessed[21], expected) > 20 * EPSILON) {
        ret_code = E_TEST_FAILED;
        goto leave_fun;
    }
    es8_pack(left_samples, h, expected);
    if (misc_rel_err(7, q_preprocessed, expected) > 20 * EPSILON)
        ret_code = E_TEST_FAILED;
leave_fun:
    free(q_preprocessed);
    free(r_preprocessed);
    return ret_code;
}

/* All single-exponential ES schemes use h^(j+1)*q^(j), including
 * boundary samples and subsampling. The tables are independent of the
 * implementation helpers. */
static INT test_es_family_preprocessing(void)
{
    static const REAL weights[3][7][7] = {
        {{0, 1, 0}, {-0.5, 0, 0.5}, {1, -2, 1}},
        {{0, 0, 1, 0, 0},
         {1.0/12, -2.0/3, 0, 2.0/3, -1.0/12},
         {-1.0/12, 4.0/3, -5.0/2, 4.0/3, -1.0/12},
         {-0.5, 1, 0, -1, 0.5}, {1, -4, 6, -4, 1}},
        {{0, 0, 0, 1, 0, 0, 0},
         {-1.0/60, 3.0/20, -3.0/4, 0, 3.0/4, -3.0/20, 1.0/60},
         {1.0/90, -3.0/20, 3.0/2, -49.0/18, 3.0/2, -3.0/20, 1.0/90},
         {1.0/8, -1, 13.0/8, 0, -13.0/8, 1, -1.0/8},
         {-1.0/6, 2, -13.0/2, 28.0/3, -13.0/2, 2, -1.0/6},
         {-0.5, 2, -2.5, 0, 2.5, -2, 0.5},
         {1, -6, 15, -20, 15, -6, 1}}
    };
    const nse_discretization_t schemes[3] = {
        nse_discretization_ES4, nse_discretization_ES6, nse_discretization_ES8
    };
    const REAL steps[2] = {0.07, 1e-100};
    COMPLEX samples[9], *qp = NULL, *rp = NULL;
    INT ret_code = SUCCESS;

    for (UINT n=0; n<9; n++)
        samples[n] = 0.17+0.023*n*n+(COMPLEX)I*(0.09-0.04*n);
    for (UINT method=0; method<3; method++) {
        const UINT stride = 2*method+3;
        for (UINT step=0; step<2; step++) {
            for (UINT skip=1; skip<=2; skip++) {
                const REAL h = steps[step]*skip;
                for (INT kappa=-1; kappa<=1; kappa+=2) {
                    UINT Dsub = skip == 1 ? 9 : 5;
                    UINT first_last[2];
                    ret_code = nse_discretization_preprocess_signal(9,samples,
                            steps[step],kappa,&Dsub,&qp,&rp,first_last,
                            schemes[method]);
                    CHECK_RETCODE(ret_code, leave_fun);
                    if (Dsub != (skip == 1 ? 9U : 5U)
                            || first_last[0] != 0 || first_last[1] != 8) {
                        ret_code = E_TEST_FAILED;
                        goto leave_fun;
                    }
                    for (UINT n=0; n<Dsub; n++) {
                        for (UINT j=0; j<stride; j++) {
                            COMPLEX expected = 0.0;
                            for (UINT k=0; k<stride; k++) {
                                const INT index = (INT)(n*skip)
                                        +((INT)k-(INT)(stride/2))*(INT)skip;
                                if (index >= 0 && index < 9)
                                    expected += weights[method][j][k]*samples[index];
                            }
                            expected *= h;
                            {
                                const COMPLEX expected_r = -kappa*CONJ(expected);
                                const REAL q_error = CABS(
                                        qp[n*stride+j]-expected);
                                const REAL r_error = CABS(
                                        rp[n*stride+j]-expected_r);
                                const REAL tolerance = 2e3*EPSILON*h;
                                if (!isfinite(CREAL(qp[n*stride+j]))
                                        || !isfinite(CIMAG(qp[n*stride+j]))
                                        || !isfinite(CREAL(rp[n*stride+j]))
                                        || !isfinite(CIMAG(rp[n*stride+j]))
                                        || !isfinite(CREAL(expected))
                                        || !isfinite(CIMAG(expected))
                                        || !isfinite(CREAL(expected_r))
                                        || !isfinite(CIMAG(expected_r))
                                        || !isfinite(q_error)
                                        || !isfinite(r_error)
                                        || !isfinite(tolerance)
                                        || !(q_error <= tolerance)
                                        || !(r_error <= tolerance)) {
                                    ret_code = E_TEST_FAILED;
                                    goto leave_fun;
                                }
                            }
                        }
                    }
                    free(qp);
                    free(rp);
                    qp = rp = NULL;
                }
            }
        }
    }
leave_fun:
    free(qp);
    free(rp);
    return ret_code;
}

/* Constant potentials have no time derivatives: every ES order must
 * reproduce exp(h*Q) and its lambda derivative, as computed by BO. */
static INT test_es_family_constant(void)
{
    const nse_discretization_t schemes[3] = {
        nse_discretization_ES4, nse_discretization_ES6, nse_discretization_ES8
    };
    const REAL h = 0.13;
    const COMPLEX value = 0.32-0.09*(COMPLEX)I;
    const COMPLEX lambda[2] = {0.0, 0.41+0.17*(COMPLEX)I};
    INT ret_code;

    for (UINT method=0; method<3; method++) {
        const UINT stride = 2*method+3;
        for (INT kappa=-1; kappa<=1; kappa+=2) {
            COMPLEX q[7] = {0}, r[7] = {0}, es[16], bo[16];
            const COMPLEX r_value = -kappa*CONJ(value);
            q[0] = h*value;
            r[0] = h*r_value;
            for (UINT derivative=0; derivative<=1; derivative++) {
                const UINT len = derivative ? 16 : 8;
                ret_code = nse_scatter_matrix(stride,q,r,h,kappa,2,lambda,
                        es,NULL,schemes[method],derivative);
                CHECK_RETCODE(ret_code, leave_fun);
                ret_code = nse_scatter_matrix(1,&value,&r_value,h,kappa,2,
                        lambda,bo,NULL,nse_discretization_BO,derivative);
                CHECK_RETCODE(ret_code, leave_fun);
                for (UINT j=0; j<len; j++) {
                    if (!isfinite(CREAL(es[j])) || !isfinite(CIMAG(es[j]))
                            || !isfinite(CREAL(bo[j]))
                            || !isfinite(CIMAG(bo[j])))
                        return E_TEST_FAILED;
                    {
                        const REAL error = CABS(es[j]-bo[j]);
                        const REAL tolerance = 500*EPSILON*(1+CABS(bo[j]));
                        if (!isfinite(error) || !isfinite(tolerance)
                                || !(error <= tolerance))
                            return E_TEST_FAILED;
                    }
                }
            }
            ret_code = nse_scatter_matrix_pade(stride,q,r,h,kappa,2,lambda,
                    es,NULL,schemes[method],1,0);
            CHECK_RETCODE(ret_code, leave_fun);
            for (UINT i=0; i<2; i++) {
                const COMPLEX z0 = -(COMPLEX)I*h*lambda[i];
                const COMPLEX z1 = h*value;
                const COMPLEX z2 = h*r_value;
                const COMPLEX delta = z0*z0+z1*z2;
                const COMPLEX denominator = 1.0-delta/4.0;
                const COMPLEX expected[4] = {
                    (1.0+delta/4.0+z0)/denominator,
                    z1/denominator, z2/denominator,
                    (1.0+delta/4.0-z0)/denominator
                };
                REAL error;
                for (UINT j=0; j<4; j++) {
                    if (!isfinite(CREAL(es[4*i+j]))
                            || !isfinite(CIMAG(es[4*i+j]))
                            || !isfinite(CREAL(expected[j]))
                            || !isfinite(CIMAG(expected[j])))
                        return E_TEST_FAILED;
                }
                error = misc_rel_err(4,&es[4*i],expected);
                if (!isfinite(error) || !(error <= 500*EPSILON))
                    return E_TEST_FAILED;
            }
            {
                const REAL invariant_error = FABS(CABS(es[0])*CABS(es[0])
                        +kappa*CABS(es[1])*CABS(es[1])-1.0);
                if (!isfinite(CREAL(es[0])) || !isfinite(CIMAG(es[0]))
                        || !isfinite(CREAL(es[1]))
                        || !isfinite(CIMAG(es[1]))
                        || !isfinite(invariant_error)
                        || !(invariant_error <= 1e-12))
                    return E_TEST_FAILED;
            }
        }
    }
    return SUCCESS;
leave_fun:
    return ret_code;
}

static INT test_step(const INT kappa, const UINT pade_degree)
{
    const REAL h = 0.13, delta = 1e-6;
    const COMPLEX lambda = 0.31 + 0.17 * I;
    const COMPLEX real_lambda = 0.31;
    const COMPLEX samples[7] = {0.31 - 0.11 * I, 0.43 + 0.07 * I, 0.48 - 0.05 * I, 0.53 + 0.14 * I,
                                0.46 - 0.19 * I, 0.39 + 0.08 * I, 0.28 - 0.03 * I};
    COMPLEX rsamples[7], q[7], r[7], M[8], Mp[4], Mm[4], Mn[4];
    INT W = 0, ret_code;
    for (UINT i = 0; i < 7; i++)
        rsamples[i] = -kappa * CONJ(samples[i]);
    es8_pack(samples, h, q);
    es8_pack(rsamples, h, r);
    ret_code =
        test_scatter_matrix(7, q, r, h, kappa, 1, &lambda, M, NULL,
                nse_discretization_ES8, pade_degree, 1);
    CHECK_RETCODE(ret_code, leave_fun);
    {
        const COMPLEX lp = lambda + delta, lm = lambda - delta;
        ret_code =
            test_scatter_matrix(7, q, r, h, kappa, 1, &lp, Mp, NULL,
                    nse_discretization_ES8, pade_degree, 0);
        CHECK_RETCODE(ret_code, leave_fun);
        ret_code =
            test_scatter_matrix(7, q, r, h, kappa, 1, &lm, Mm, NULL,
                    nse_discretization_ES8, pade_degree, 0);
        CHECK_RETCODE(ret_code, leave_fun);
    }
    for (UINT i = 0; i < 4; i++)
        Mp[i] = (Mp[i] - Mm[i]) / (2.0 * delta);
    {
        REAL error;
        for (UINT i=0; i<4; i++) {
            if (!isfinite(CREAL(M[4+i])) || !isfinite(CIMAG(M[4+i]))
                    || !isfinite(CREAL(Mp[i])) || !isfinite(CIMAG(Mp[i])))
                return E_TEST_FAILED;
        }
        error = misc_rel_err(4,&M[4],Mp);
        if (!isfinite(error) || !(error <= 2e-9))
            return E_TEST_FAILED;
    }
    ret_code =
        test_scatter_matrix(7, q, r, h, kappa, 1, &real_lambda, Mn, NULL,
                nse_discretization_ES8, pade_degree, 0);
    CHECK_RETCODE(ret_code, leave_fun);
    {
        const REAL invariant_error = FABS(CABS(Mn[0])*CABS(Mn[0])
                +kappa*CABS(Mn[1])*CABS(Mn[1])-1.0);
        if (!isfinite(CREAL(Mn[0])) || !isfinite(CIMAG(Mn[0]))
                || !isfinite(CREAL(Mn[1])) || !isfinite(CIMAG(Mn[1]))
                || !isfinite(invariant_error)
                || !(invariant_error <= 1e-12))
            return E_TEST_FAILED;
    }
    ret_code = test_scatter_matrix(7, q, r, h, kappa, 1, &lambda, Mn, &W,
            nse_discretization_ES8, pade_degree, 0);
    CHECK_RETCODE(ret_code, leave_fun);
    for (UINT i = 0; i < 4; i++)
        Mn[i] *= POW(2, W);
    {
        REAL error;
        for (UINT i=0; i<4; i++) {
            if (!isfinite(CREAL(M[i])) || !isfinite(CIMAG(M[i]))
                    || !isfinite(CREAL(Mn[i])) || !isfinite(CIMAG(Mn[i])))
                return E_TEST_FAILED;
        }
        error = misc_rel_err(4,M,Mn);
        if (!isfinite(error) || !(error <= 100*EPSILON))
            return E_TEST_FAILED;
    }
leave_fun:
    return ret_code;
}

static INT test_all_slow_pade_paths(void)
{
    const nse_discretization_t schemes[3] = {
        nse_discretization_ES4, nse_discretization_ES6,
        nse_discretization_ES8
    };
    const REAL h = 0.06, delta = 1e-6;
    const REAL T[2] = {-0.24, 0.24};
    const COMPLEX lambda[2] = {
        0.27+0.19*(COMPLEX)I, -0.16+0.31*(COMPLEX)I
    };
    const COMPLEX continuous_lambda[2] = {-0.67,0.91};
    COMPLEX samples[9];
    COMPLEX *q = NULL, *r = NULL;
    INT ret_code = SUCCESS;

    for (UINT n=0; n<9; n++)
        samples[n] = 0.23+0.017*n*n+(COMPLEX)I*(0.11-0.026*n);
    for (UINT method=0; method<3; method++) {
        const UINT stride = 2*method+3;
        for (INT kappa=-1; kappa<=1; kappa+=2) {
            UINT Dsub = 9, first_last[2];
            ret_code = nse_discretization_preprocess_signal(9,samples,h,
                    kappa,&Dsub,&q,&r,first_last,schemes[method]);
            CHECK_RETCODE(ret_code, leave_fun);
            if (Dsub != 9 || first_last[0] != 0 || first_last[1] != 8) {
                ret_code = E_TEST_FAILED;
                goto leave_fun;
            }
            for (UINT degree=0; degree<=7; degree++) {
                COMPLEX matrix[16], normalized[16], plus[4], minus[4];
                COMPLEX bound_state = 0.17+4.0*(COMPLEX)I;
                COMPLEX a[2], aprime[2], b[2];
                INT W[2] = {0}, Ws = 0;

                ret_code = test_scatter_matrix(Dsub*stride,q,r,h,kappa,2,
                        lambda,matrix,NULL,schemes[method],degree,1);
                CHECK_RETCODE(ret_code, leave_fun);
                ret_code = test_scatter_matrix(Dsub*stride,q,r,h,kappa,2,
                        lambda,normalized,W,schemes[method],degree,1);
                CHECK_RETCODE(ret_code, leave_fun);
                for (UINT i=0; i<2; i++) {
                    for (UINT j=0; j<8; j++) {
                        const COMPLEX scaled = normalized[8*i+j]*POW(2,W[i]);
                        const REAL error = CABS(matrix[8*i+j]-scaled);
                        const REAL tolerance = 500*EPSILON
                                *(1+CABS(matrix[8*i+j]));
                        if (!isfinite(CREAL(matrix[8*i+j]))
                                || !isfinite(CIMAG(matrix[8*i+j]))
                                || !isfinite(CREAL(scaled))
                                || !isfinite(CIMAG(scaled))
                                || !isfinite(error) || !isfinite(tolerance)
                                || !(error <= tolerance)) {
                            ret_code = E_TEST_FAILED;
                            goto leave_fun;
                        }
                    }
                    if (W[i] == 0 && memcmp(&matrix[8*i],&normalized[8*i],
                            8*sizeof(COMPLEX)) != 0) {
                        ret_code = E_TEST_FAILED;
                        goto leave_fun;
                    }
                }
                {
                    const COMPLEX lambda_plus = lambda[0]+delta;
                    const COMPLEX lambda_minus = lambda[0]-delta;
                    ret_code = test_scatter_matrix(Dsub*stride,q,r,h,kappa,
                            1,&lambda_plus,plus,NULL,schemes[method],degree,0);
                    CHECK_RETCODE(ret_code, leave_fun);
                    ret_code = test_scatter_matrix(Dsub*stride,q,r,h,kappa,
                            1,&lambda_minus,minus,NULL,schemes[method],degree,0);
                    CHECK_RETCODE(ret_code, leave_fun);
                    for (UINT j=0; j<4; j++) {
                        const COMPLEX finite_difference =
                                (plus[j]-minus[j])/(2.0*delta);
                        const REAL error = CABS(matrix[4+j]
                                -finite_difference);
                        const REAL tolerance = 2e-8
                                *(1+CABS(finite_difference));
                        if (!isfinite(CREAL(finite_difference))
                                || !isfinite(CIMAG(finite_difference))
                                || !isfinite(error) || !isfinite(tolerance)
                                || !(error <= tolerance)) {
                            ret_code = E_TEST_FAILED;
                            goto leave_fun;
                        }
                    }
                }
                ret_code = test_scatter_bound_states(Dsub*stride,q,r,T,
                        bound_state,&a[0],&aprime[0],&b[0],NULL,
                        schemes[method],degree);
                CHECK_RETCODE(ret_code, leave_fun);
                ret_code = test_scatter_bound_states(Dsub*stride,q,r,T,
                        bound_state,&a[1],&aprime[1],&b[1],&Ws,
                        schemes[method],degree);
                CHECK_RETCODE(ret_code, leave_fun);
                if (Ws == 0) {
                    ret_code = E_TEST_FAILED;
                    goto leave_fun;
                }
                {
                    const COMPLEX scaled_a = a[1]*POW(2,Ws);
                    const COMPLEX scaled_aprime = aprime[1]*POW(2,Ws);
                    const REAL errors[3] = {CABS(a[0]-scaled_a),
                        CABS(aprime[0]-scaled_aprime),CABS(b[0]-b[1])};
                    const REAL tolerances[3] = {
                        500*EPSILON*(1+CABS(a[0])),
                        500*EPSILON*(1+CABS(aprime[0])),
                        500*EPSILON*(1+CABS(b[0]))
                    };
                    for (UINT j=0; j<3; j++) {
                        if (!isfinite(errors[j]) || !isfinite(tolerances[j])
                                || !(errors[j] <= tolerances[j])) {
                            ret_code = E_TEST_FAILED;
                            goto leave_fun;
                        }
                    }
                }
                for (UINT normalization=0; normalization<=1;
                        normalization++) {
                    COMPLEX full[8], H11[2], H21[2];
                    INT Wfull[2] = {0}, Wcolumn[2] = {0};
                    akns_discretization_t akns_discretization;
                    INT * const Wfull_ptr = normalization ? Wfull : NULL;
                    INT * const Wcolumn_ptr = normalization ? Wcolumn : NULL;

                    ret_code = test_scatter_matrix(Dsub*stride,q,r,h,kappa,
                            2,continuous_lambda,full,Wfull_ptr,
                            schemes[method],degree,0);
                    CHECK_RETCODE(ret_code, leave_fun);
                    ret_code = nse_discretization_to_akns_discretization(
                            schemes[method],&akns_discretization);
                    CHECK_RETCODE(ret_code, leave_fun);
                    ret_code = akns_scatter_matrix_first_column(Dsub*stride,
                            q,r,h,2,continuous_lambda,H11,H21,Wcolumn_ptr,
                            akns_discretization,degree);
                    CHECK_RETCODE(ret_code, leave_fun);
                    for (UINT i=0; i<2; i++) {
                        if (memcmp(&H11[i],&full[4*i],sizeof(COMPLEX)) != 0
                                || memcmp(&H21[i],&full[4*i+2],
                                    sizeof(COMPLEX)) != 0
                                || (normalization
                                    && Wcolumn[i] != Wfull[i])) {
                            ret_code = E_TEST_FAILED;
                            goto leave_fun;
                        }
                    }
                }
            }
            free(q);
            free(r);
            q = r = NULL;
        }
    }

leave_fun:
    free(q);
    free(r);
    return ret_code;
}

/* Exercise normalization outside its no-op range. A zero potential and an
 * imaginary spectral point produce reciprocal growing and decaying diagonal
 * entries, so both high and low finite magnitudes are reconstructed. */
static INT test_slow_ES_normalization_rescaling(void)
{
    const nse_discretization_t schemes[3] = {
        nse_discretization_ES4, nse_discretization_ES6,
        nse_discretization_ES8
    };
    enum { nodes = 32 };
    const REAL h = 0.05;
    const COMPLEX lambda = 10.0*(COMPLEX)I;
    COMPLEX q[7*nodes] = {0}, r[7*nodes] = {0};
    INT ret_code = SUCCESS;

    for (UINT method=0; method<3; method++) {
        const UINT stride = 2*method+3;
        const UINT D = nodes*stride;

        for (INT kappa=-1; kappa<=1; kappa+=2) {
            for (UINT degree=0; degree<=7; degree++) {
                COMPLEX unnormalized[8], normalized[8];
                INT W = 0;

                ret_code = test_scatter_matrix(D,q,r,h,kappa,1,&lambda,
                        unnormalized,NULL,schemes[method],degree,1);
                CHECK_RETCODE(ret_code, leave_fun);
                ret_code = test_scatter_matrix(D,q,r,h,kappa,1,&lambda,
                        normalized,&W,schemes[method],degree,1);
                CHECK_RETCODE(ret_code, leave_fun);
                if (W == 0) {
                    ret_code = E_TEST_FAILED;
                    goto leave_fun;
                }
                for (UINT j=0; j<8; j++) {
                    const COMPLEX reconstructed = normalized[j]*POW(2,W);
                    const REAL error = CABS(unnormalized[j]-reconstructed);
                    const REAL tolerance = 2000*EPSILON
                            *(1+CABS(unnormalized[j]));
                    if (!isfinite(CREAL(unnormalized[j]))
                            || !isfinite(CIMAG(unnormalized[j]))
                            || !isfinite(CREAL(normalized[j]))
                            || !isfinite(CIMAG(normalized[j]))
                            || !isfinite(CREAL(reconstructed))
                            || !isfinite(CIMAG(reconstructed))
                            || !isfinite(error) || !isfinite(tolerance)
                            || !(error <= tolerance)) {
                        ret_code = E_TEST_FAILED;
                        goto leave_fun;
                    }
                }
            }
        }
    }

leave_fun:
    return ret_code;
}

static INT test_slow_ES_nonfinite_normalization(void)
{
    const nse_discretization_t schemes[3] = {
        nse_discretization_ES4, nse_discretization_ES6,
        nse_discretization_ES8
    };
    const COMPLEX lambda = 0.23;
    COMPLEX q[7] = {NAN}, r[7] = {0};
    INT ret_code = SUCCESS;

    for (UINT method=0; method<3; method++) {
        const UINT D = 2*method+3;
        akns_discretization_t akns_discretization;

        ret_code = nse_discretization_to_akns_discretization(
                schemes[method],&akns_discretization);
        CHECK_RETCODE(ret_code, leave_fun);

        for (UINT degree=0; degree<=7; degree++) {
            COMPLEX unnormalized[4], normalized[4];
            COMPLEX H11, H21;
            UINT nonfinite_count = 0;
            INT W = 0, W_first_column = 0;

            ret_code = test_scatter_matrix(D,q,r,0.05,+1,1,&lambda,
                    unnormalized,NULL,schemes[method],degree,0);
            CHECK_RETCODE(ret_code, leave_fun);
            ret_code = test_scatter_matrix(D,q,r,0.05,+1,1,&lambda,
                    normalized,&W,schemes[method],degree,0);
            CHECK_RETCODE(ret_code, leave_fun);
            ret_code = akns_scatter_matrix_first_column(D,q,r,0.05,1,
                    &lambda,&H11,&H21,&W_first_column,
                    akns_discretization,degree);
            CHECK_RETCODE(ret_code, leave_fun);
            for (UINT j=0; j<4; j++) {
                const int unnormalized_finite =
                        isfinite(CREAL(unnormalized[j]))
                        && isfinite(CIMAG(unnormalized[j]));
                const int normalized_finite = isfinite(CREAL(normalized[j]))
                        && isfinite(CIMAG(normalized[j]));

                if (unnormalized_finite != normalized_finite) {
                    ret_code = E_TEST_FAILED;
                    goto leave_fun;
                }
                if (!normalized_finite)
                    nonfinite_count++;
            }
            if ((isfinite(CREAL(H11)) && isfinite(CIMAG(H11)))
                        != (isfinite(CREAL(normalized[0]))
                            && isfinite(CIMAG(normalized[0])))
                    || (isfinite(CREAL(H21)) && isfinite(CIMAG(H21)))
                        != (isfinite(CREAL(normalized[2]))
                            && isfinite(CIMAG(normalized[2])))
                    || nonfinite_count == 0 || W != 0
                    || W_first_column != W) {
                ret_code = E_TEST_FAILED;
                goto leave_fun;
            }
        }
    }

leave_fun:
    return ret_code;
}

static INT test_slow_ES_first_column_scaling(void)
{
    const nse_discretization_t schemes[3] = {
        nse_discretization_ES4, nse_discretization_ES6,
        nse_discretization_ES8
    };
    enum { nodes = 32 };
    const COMPLEX lambda = 0.0;
    COMPLEX q[7*nodes], r[7*nodes];
    INT ret_code = SUCCESS;

    for (UINT method=0; method<3; method++) {
        const UINT stride = 2*method+3;
        const UINT D = nodes*stride;
        akns_discretization_t akns_discretization;

        ret_code = nse_discretization_to_akns_discretization(
                schemes[method],&akns_discretization);
        CHECK_RETCODE(ret_code, leave_fun);
        for (INT kappa=-1; kappa<=1; kappa+=2) {
            memset(q,0,sizeof(q));
            memset(r,0,sizeof(r));
            for (UINT node=0; node<nodes; node++) {
                q[node*stride] = 0.4;
                r[node*stride] = -0.4*kappa;
            }
            for (UINT degree=0; degree<=7; degree++) {
                COMPLEX full[4], H11, H21;
                INT Wfull = 0, Wcolumn = 0;

                ret_code = test_scatter_matrix(D,q,r,0.05,kappa,1,&lambda,
                        full,&Wfull,schemes[method],degree,0);
                CHECK_RETCODE(ret_code, leave_fun);
                ret_code = akns_scatter_matrix_first_column(D,q,r,0.05,1,
                        &lambda,&H11,&H21,&Wcolumn,akns_discretization,
                        degree);
                CHECK_RETCODE(ret_code, leave_fun);
                if (Wfull != Wcolumn
                        || memcmp(&H11,&full[0],sizeof(COMPLEX)) != 0
                        || memcmp(&H21,&full[2],sizeof(COMPLEX)) != 0
                        || (kappa == -1 && Wcolumn == 0)) {
                    ret_code = E_TEST_FAILED;
                    goto leave_fun;
                }
            }
        }
    }

leave_fun:
    return ret_code;
}

static INT test_constant_and_zero(const INT kappa)
{
    const REAL h = 0.09;
    const COMPLEX lambda = 0.41, value = 0.32 - 0.09 * I;
    COMPLEX samples[7], rsamples[7], q[7], r[7], es8[4], bo[4];
    INT ret_code;
    for (UINT i = 0; i < 7; i++) {
        samples[i] = value;
        rsamples[i] = -kappa * CONJ(value);
    }
    es8_pack(samples, h, q);
    es8_pack(rsamples, h, r);
    ret_code =
        nse_scatter_matrix(7, q, r, h, kappa, 1, &lambda, es8, NULL, nse_discretization_ES8, 0);
    CHECK_RETCODE(ret_code, leave_fun);
    ret_code = nse_scatter_matrix(1, samples, rsamples, h, kappa, 1, &lambda, bo, NULL,
                                  nse_discretization_BO, 0);
    CHECK_RETCODE(ret_code, leave_fun);
    if (misc_rel_err(4, es8, bo) > 100 * EPSILON)
        return E_TEST_FAILED;
    memset(q, 0, sizeof(q));
    memset(r, 0, sizeof(r));
    ret_code =
        nse_scatter_matrix(7, q, r, h, kappa, 1, &lambda, es8, NULL, nse_discretization_ES8, 0);
    CHECK_RETCODE(ret_code, leave_fun);
    bo[0] = CEXP(-I * lambda * h);
    bo[1] = bo[2] = 0.0;
    bo[3] = CEXP(I * lambda * h);
    if (misc_rel_err(4, es8, bo) > 100 * EPSILON)
        return E_TEST_FAILED;
leave_fun:
    return ret_code;
}

/* Compare complete blocks and partial last blocks with a product of
 * independently evaluated single-node transitions, including U'. */
static INT test_slow_ES_block_composition(void)
{
    const UINT sizes[] = {2,31,32,33,63,64,65};
    const nse_discretization_t schemes[] = {
        nse_discretization_ES4,nse_discretization_ES6,nse_discretization_ES8
    };
    const COMPLEX lambda[] = {-0.4,0.6+0.13*(COMPLEX)I};
    const REAL h = 0.02;
    COMPLEX samples[65], *q = NULL, *r = NULL;
    INT ret_code = SUCCESS;

    for (UINT size=0; size<sizeof(sizes)/sizeof(sizes[0]); size++) {
        const UINT N = sizes[size];
        for (UINT n=0; n<N; n++) {
            const REAL t = n*h;
            samples[n] = 0.3+0.12*SIN(3*t)+0.2*(COMPLEX)I*COS(t);
        }
        for (UINT method=0; method<3; method++) {
            const UINT stride = 2*method+3;
            for (INT kappa=-1; kappa<=1; kappa+=2) {
                UINT Dsub = N, first_last[2];
                ret_code = nse_discretization_preprocess_signal(N,samples,h,
                        kappa,&Dsub,&q,&r,first_last,schemes[method]);
                CHECK_RETCODE(ret_code,leave_fun);
                for (UINT degree=0; degree<=7; degree++) {
                    for (UINT point=0; point<2; point++) {
                        COMPLEX reference[8] = {1,0,0,1,0,0,0,0};
                        for (UINT n=0; n<N; n++) {
                            COMPLEX U[8], next[8] = {0};
                            ret_code = test_scatter_matrix(stride,q+stride*n,
                                    r+stride*n,h,kappa,1,&lambda[point],U,
                                    NULL,schemes[method],degree,1);
                            CHECK_RETCODE(ret_code,leave_fun);
                            for (UINT row=0; row<2; row++) {
                                for (UINT col=0; col<2; col++) {
                                    for (UINT k=0; k<2; k++) {
                                        next[2*row+col] += U[2*row+k]
                                                *reference[2*k+col];
                                        next[4+2*row+col] += U[4+2*row+k]
                                                *reference[2*k+col]
                                                +U[2*row+k]*reference[4+2*k+col];
                                    }
                                }
                            }
                            memcpy(reference,next,sizeof(reference));
                        }
                        for (UINT derivative=0; derivative<=1; derivative++) {
                            for (UINT normalize=0; normalize<=1; normalize++) {
                                COMPLEX actual[8];
                                INT W = 0;
                                ret_code = test_scatter_matrix(N*stride,q,r,h,
                                        kappa,1,&lambda[point],actual,
                                        normalize ? &W : NULL,schemes[method],
                                        degree,derivative);
                                CHECK_RETCODE(ret_code,leave_fun);
                                for (UINT j=0; j<(derivative ? 8 : 4); j++) {
                                    const COMPLEX value = actual[j]*POW(2,W);
                                    const REAL tolerance = 128*(N+1)*EPSILON
                                            *(1+CABS(reference[j]));
                                    if (!isfinite(CREAL(value))
                                            || !isfinite(CIMAG(value))
                                            || !(CABS(value-reference[j]) <= tolerance)) {
                                        ret_code = E_TEST_FAILED;
                                        goto leave_fun;
                                    }
                                }
                            }
                        }
                    }
                }
                free(q);
                free(r);
                q = NULL;
                r = NULL;
            }
        }
    }
leave_fun:
    free(q);
    free(r);
    return ret_code;
}

INT main(void)
{
    const COMPLEX q_bad[6] = {0}, r_bad[6] = {0}, lambda = 0.3;
    const COMPLEX q_singular[3] = {0}, r_singular[3] = {0};
    const COMPLEX singular_lambda = 20.0*(COMPLEX)I;
    COMPLEX result[4];
    INT ret_code;
    ret_code = test_paper_coefficients();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_es_family_traceless_coefficients();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_exact_scalar_pair_grid();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_exact_scalar_pair_shared_hyperbolics();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_exact_scalar_pair_signed_zeros();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_exact_scalar_pair_derivative_grid();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_exact_scalar_pair_extremes();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_stencil_and_boundaries();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_es_family_preprocessing();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_es_family_constant();
    CHECK_RETCODE(ret_code, failure);
    if (nse_scatter_matrix(6, q_bad, r_bad, 0.1, +1, 1, &lambda, result, NULL,
                           nse_discretization_ES8, 0) == SUCCESS)
        return EXIT_FAILURE;
    if (nse_scatter_matrix_pade(3,q_singular,r_singular,0.1,+1,1,
                &lambda,result,NULL,nse_discretization_ES4,0,0) == SUCCESS)
        return EXIT_FAILURE;
    if (nse_scatter_matrix_pade(3,q_singular,r_singular,0.1,+1,1,
                &lambda,result,NULL,nse_discretization_ES4,8,0) == SUCCESS)
        return EXIT_FAILURE;
    if (nse_scatter_matrix_pade(3,q_singular,r_singular,0.1,+1,1,
                &lambda,result,NULL,nse_discretization_BO,1,0) == SUCCESS)
        return EXIT_FAILURE;
    if (nse_scatter_matrix_pade(3,q_singular,r_singular,0.1,+1,1,
                &singular_lambda,result,NULL,nse_discretization_ES4,1,0)
            == SUCCESS)
        return EXIT_FAILURE;
    ret_code = test_step(+1,0);
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_step(-1,0);
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_step(+1,5);
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_step(-1,5);
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_all_slow_pade_paths();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_slow_ES_block_composition();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_slow_ES_normalization_rescaling();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_slow_ES_nonfinite_normalization();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_slow_ES_first_column_scaling();
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_constant_and_zero(+1);
    CHECK_RETCODE(ret_code, failure);
    ret_code = test_constant_and_zero(-1);
    CHECK_RETCODE(ret_code, failure);
    return EXIT_SUCCESS;
failure:
    return EXIT_FAILURE;
}
